name: Windows Runner USA Check

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-2022

    steps:
      - name: Check Windows
        shell: powershell
        run: |
          Write-Host "===== WINDOWS ====="
          Write-Host "Computer: $env:COMPUTERNAME"
          Write-Host "User: $env:USERNAME"
          Write-Host "OS:"
          (Get-CimInstance Win32_OperatingSystem).Caption

      - name: Check Public IP
        shell: powershell
        run: |
          $ip = Invoke-RestMethod "https://api.ipify.org"
          Write-Host "===== PUBLIC IP ====="
          Write-Host $ip

          $info = Invoke-RestMethod "https://ipinfo.io/$ip/json"

          Write-Host "===== LOCATION ====="
          Write-Host "Country: $($info.country)"
          Write-Host "Region: $($info.region)"
          Write-Host "City: $($info.city)"
          Write-Host "Organization: $($info.org)"
